# Generated by Django 3.2.3 on 2021-06-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idCargo', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ID Cargo')),
                ('nomCargo', models.CharField(max_length=30, verbose_name='Nombre Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('idCompania', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Compañia')),
                ('nomComp', models.CharField(max_length=35, verbose_name='Nombre Compañía')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ID Comuna')),
                ('nomCom', models.CharField(max_length=20, verbose_name='Nombre Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut')),
                ('dv', models.CharField(max_length=1, verbose_name='Dígito verificador')),
                ('pnombre', models.CharField(max_length=25, verbose_name='Primer nombre')),
                ('snombre', models.CharField(blank=True, max_length=25, null=True, verbose_name='Segundo nombre')),
                ('appaterno', models.CharField(max_length=25, verbose_name='Apellido paterno')),
                ('apmaterno', models.CharField(max_length=25, verbose_name='Apellido materno')),
                ('fono', models.IntegerField(verbose_name='Teléfono')),
                ('fecha_ing', models.DateField(verbose_name='Fecha Ingreso')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.cargo')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.compania')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.comuna')),
            ],
        ),
    ]
