# Generated by Django 3.2.3 on 2021-06-10 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('idNivelAcademico', models.IntegerField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nivelAcademico', models.CharField(max_length=25, verbose_name='Nivel Academico')),
            ],
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('rut', models.IntegerField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut')),
                ('pnombre', models.CharField(max_length=25, verbose_name='Primer nombre')),
                ('snombre', models.CharField(blank=True, max_length=25, null=True, verbose_name='Segundo nombre')),
                ('appaterno', models.CharField(max_length=25, verbose_name='Apellido paterno')),
                ('apmaterno', models.CharField(max_length=25, verbose_name='Apellido materno')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('nivelAcademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.comuna')),
            ],
        ),
    ]
