# Generated by Django 3.2.3 on 2021-06-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_nivelacademico_postulante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NivelAcademico',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='nivelAcademico',
        ),
        migrations.AddField(
            model_name='postulante',
            name='edad',
            field=models.IntegerField(default=2, max_length=2, verbose_name='Edad'),
            preserve_default=False,
        ),
    ]
