# Generated by Django 3.2.3 on 2021-06-10 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_auto_20210609_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('idNivelAcademico', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Nivel Academico')),
                ('nivelAcademico', models.CharField(max_length=20, verbose_name='Nivel Academico')),
            ],
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='direccion',
        ),
        migrations.AddField(
            model_name='postulante',
            name='nivelAcademico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appweb.nivelacademico'),
            preserve_default=False,
        ),
    ]
