# Generated by Django 3.2.3 on 2021-06-10 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0004_auto_20210609_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulante',
            old_name='nivelAcademico',
            new_name='nivel',
        ),
    ]
