# Generated by Django 3.2.3 on 2021-06-10 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_rename_nivelacademico_postulante_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='rut',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.nivelacademico', verbose_name='Nivel Academico'),
        ),
    ]
