# Generated by Django 3.2.3 on 2021-07-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0006_auto_20210610_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='compania',
        ),
        migrations.AlterField(
            model_name='personal',
            name='rut',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='rut',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut'),
        ),
        migrations.DeleteModel(
            name='Compania',
        ),
    ]
